### ISSUE TITLE
Fewer GitHub permissions to comment

### ISSUE THREAD

**Issue by TysonMN** [RehanSaeed/rehansaeed.github.io#205]
Many of your posts include comments saying that too many GitHub permissions are required to post a comment directly from the site.  I agree, and the easy workaround that I have been using is to directly comment on GitHub.

On [my blog](https://tysonwilliams.coding.blog/), I use [utterances](https://utteranc.es/) for comments (which includes hosting the comments on GitHub, fetching the correct comments on page load, allowing visitors to comment directly from a post, and linking to the issue with the comments for the a given post).

Utterances is better than your solution in that the GitHub permissions required to comment from the post are reasonable.  The permission is something like "Allow [`utterance-bot`](https://github.com/utterances-bot) comment on your behalf".

Utterances definitely has its problems though.  Chief among them is that it is not being actively maintained.  I decided to use it anyway because it was easy to set up and I think I will be able to migrate to a different commenting solution (such as a maintained fork).

Another feature that your commenting solution seems to have that utterances lacks is that the corresponding GitHub issue for each post exists before the first person comments.  Having this makes it possible to use the workaround above of directly going to GitHub to comment.

P.S.
What do you think about closing all of the issues tagged `comment`?  I don't see the advantage of having them be open.

**Comment by RehanSaeed** [comment]
I have a love hate relationship with using GitHub comments for my blog. I've had a lot of comments about permissions which I don't think can be solved due to GitHub's ver coarse grained permission model. Utterances looks ok but lack of support would worry me having come from WordPress where the lack of support for a plugin caused me to jump ship.

I think the real long term solution is to make the comments read only and provide a link to the GitHub issue where the comments are located if someone wants to comment. That way, I might even throw away the comment system I'm using and build my own far simpler one. Or just use CSS to hide the login prompt.

I did think about closing the comment issues but it looks odd for people who want to comment. You can always search comments by label if you find them annoying.

**Comment by TysonMN** [comment]
How does the seed/first comment for get created for a post on your blog?  Do you have to do something manual to create it?

**Comment by RehanSaeed** [comment]
The plugin does it for me when I login. If I hide the login button and new comment text box, I'd probably end up using the GitHub CLI to create the issue in GitHub Actions.
